=begin
#jbpm

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 7.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'date'

module JBPMAPIClient

  class TaskInstance
    attr_accessor :task_id

    attr_accessor :task_priority

    attr_accessor :task_name

    attr_accessor :task_subject

    attr_accessor :task_description

    attr_accessor :task_type

    attr_accessor :task_form

    attr_accessor :task_status

    attr_accessor :task_actual_owner

    attr_accessor :task_created_by

    attr_accessor :task_created_on

    attr_accessor :task_activation_time

    attr_accessor :task_expiration_time

    attr_accessor :task_skippable

    attr_accessor :task_workitem_id

    attr_accessor :task_process_instance_id

    attr_accessor :task_parent_id

    attr_accessor :task_process_id

    attr_accessor :task_container_id

    attr_accessor :task_pot_owners

    attr_accessor :task_excl_owners

    attr_accessor :task_business_admins

    attr_accessor :task_input_data

    attr_accessor :task_output_data


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'task_id' => :'task-id',
        :'task_priority' => :'task-priority',
        :'task_name' => :'task-name',
        :'task_subject' => :'task-subject',
        :'task_description' => :'task-description',
        :'task_type' => :'task-type',
        :'task_form' => :'task-form',
        :'task_status' => :'task-status',
        :'task_actual_owner' => :'task-actual-owner',
        :'task_created_by' => :'task-created-by',
        :'task_created_on' => :'task-created-on',
        :'task_activation_time' => :'task-activation-time',
        :'task_expiration_time' => :'task-expiration-time',
        :'task_skippable' => :'task-skippable',
        :'task_workitem_id' => :'task-workitem-id',
        :'task_process_instance_id' => :'task-process-instance-id',
        :'task_parent_id' => :'task-parent-id',
        :'task_process_id' => :'task-process-id',
        :'task_container_id' => :'task-container-id',
        :'task_pot_owners' => :'task-pot-owners',
        :'task_excl_owners' => :'task-excl-owners',
        :'task_business_admins' => :'task-business-admins',
        :'task_input_data' => :'task-input-data',
        :'task_output_data' => :'task-output-data'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'task_id' => :'Integer',
        :'task_priority' => :'Integer',
        :'task_name' => :'String',
        :'task_subject' => :'String',
        :'task_description' => :'String',
        :'task_type' => :'String',
        :'task_form' => :'String',
        :'task_status' => :'String',
        :'task_actual_owner' => :'String',
        :'task_created_by' => :'String',
        :'task_created_on' => :'DateTime',
        :'task_activation_time' => :'DateTime',
        :'task_expiration_time' => :'DateTime',
        :'task_skippable' => :'BOOLEAN',
        :'task_workitem_id' => :'Integer',
        :'task_process_instance_id' => :'Integer',
        :'task_parent_id' => :'Integer',
        :'task_process_id' => :'String',
        :'task_container_id' => :'String',
        :'task_pot_owners' => :'Array<String>',
        :'task_excl_owners' => :'Array<String>',
        :'task_business_admins' => :'Array<String>',
        :'task_input_data' => :'Hash<String, Object>',
        :'task_output_data' => :'Hash<String, Object>'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'task-id')
        self.task_id = attributes[:'task-id']
      end

      if attributes.has_key?(:'task-priority')
        self.task_priority = attributes[:'task-priority']
      end

      if attributes.has_key?(:'task-name')
        self.task_name = attributes[:'task-name']
      end

      if attributes.has_key?(:'task-subject')
        self.task_subject = attributes[:'task-subject']
      end

      if attributes.has_key?(:'task-description')
        self.task_description = attributes[:'task-description']
      end

      if attributes.has_key?(:'task-type')
        self.task_type = attributes[:'task-type']
      end

      if attributes.has_key?(:'task-form')
        self.task_form = attributes[:'task-form']
      end

      if attributes.has_key?(:'task-status')
        self.task_status = attributes[:'task-status']
      end

      if attributes.has_key?(:'task-actual-owner')
        self.task_actual_owner = attributes[:'task-actual-owner']
      end

      if attributes.has_key?(:'task-created-by')
        self.task_created_by = attributes[:'task-created-by']
      end

      if attributes.has_key?(:'task-created-on')
        self.task_created_on = attributes[:'task-created-on']
      end

      if attributes.has_key?(:'task-activation-time')
        self.task_activation_time = attributes[:'task-activation-time']
      end

      if attributes.has_key?(:'task-expiration-time')
        self.task_expiration_time = attributes[:'task-expiration-time']
      end

      if attributes.has_key?(:'task-skippable')
        self.task_skippable = attributes[:'task-skippable']
      end

      if attributes.has_key?(:'task-workitem-id')
        self.task_workitem_id = attributes[:'task-workitem-id']
      end

      if attributes.has_key?(:'task-process-instance-id')
        self.task_process_instance_id = attributes[:'task-process-instance-id']
      end

      if attributes.has_key?(:'task-parent-id')
        self.task_parent_id = attributes[:'task-parent-id']
      end

      if attributes.has_key?(:'task-process-id')
        self.task_process_id = attributes[:'task-process-id']
      end

      if attributes.has_key?(:'task-container-id')
        self.task_container_id = attributes[:'task-container-id']
      end

      if attributes.has_key?(:'task-pot-owners')
        if (value = attributes[:'task-pot-owners']).is_a?(Array)
          self.task_pot_owners = value
        end
      end

      if attributes.has_key?(:'task-excl-owners')
        if (value = attributes[:'task-excl-owners']).is_a?(Array)
          self.task_excl_owners = value
        end
      end

      if attributes.has_key?(:'task-business-admins')
        if (value = attributes[:'task-business-admins']).is_a?(Array)
          self.task_business_admins = value
        end
      end

      if attributes.has_key?(:'task-input-data')
        if (value = attributes[:'task-input-data']).is_a?(Hash)
          self.task_input_data = value
        end
      end

      if attributes.has_key?(:'task-output-data')
        if (value = attributes[:'task-output-data']).is_a?(Hash)
          self.task_output_data = value
        end
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          task_id == o.task_id &&
          task_priority == o.task_priority &&
          task_name == o.task_name &&
          task_subject == o.task_subject &&
          task_description == o.task_description &&
          task_type == o.task_type &&
          task_form == o.task_form &&
          task_status == o.task_status &&
          task_actual_owner == o.task_actual_owner &&
          task_created_by == o.task_created_by &&
          task_created_on == o.task_created_on &&
          task_activation_time == o.task_activation_time &&
          task_expiration_time == o.task_expiration_time &&
          task_skippable == o.task_skippable &&
          task_workitem_id == o.task_workitem_id &&
          task_process_instance_id == o.task_process_instance_id &&
          task_parent_id == o.task_parent_id &&
          task_process_id == o.task_process_id &&
          task_container_id == o.task_container_id &&
          task_pot_owners == o.task_pot_owners &&
          task_excl_owners == o.task_excl_owners &&
          task_business_admins == o.task_business_admins &&
          task_input_data == o.task_input_data &&
          task_output_data == o.task_output_data
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [task_id, task_priority, task_name, task_subject, task_description, task_type, task_form, task_status, task_actual_owner, task_created_by, task_created_on, task_activation_time, task_expiration_time, task_skippable, task_workitem_id, task_process_instance_id, task_parent_id, task_process_id, task_container_id, task_pot_owners, task_excl_owners, task_business_admins, task_input_data, task_output_data].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = JBPMAPIClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
