=begin
#jbpm

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 7.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for JBPMAPIClient::KIEServerCoreApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'KIEServerCoreApi' do
  before do
    # run before each test
    @instance = JBPMAPIClient::KIEServerCoreApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of KIEServerCoreApi' do
    it 'should create an instance of KIEServerCoreApi' do
      expect(@instance).to be_instance_of(JBPMAPIClient::KIEServerCoreApi)
    end
  end

  # unit tests for create_container
  # Creates (deploys) new KIE container to this server
  # 
  # @param id Container id to be assigned to deployed KIE Container
  # @param body KIE Container resource to be deployed as KieContainerResource
  # @param [Hash] opts the optional parameters
  # @return [Response]
  describe 'create_container test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for dispose_container
  # Disposes (undeploys) container with given id
  # 
  # @param id Container id to be disposed (undeployed)
  # @param [Hash] opts the optional parameters
  # @return [Response]
  describe 'dispose_container test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_container_info
  # Retrieves container with given id
  # 
  # @param id Container id to be retrieved
  # @param [Hash] opts the optional parameters
  # @return [Response]
  describe 'get_container_info test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_info
  # Retrieves KIE Server information - id, name, location, capabilities, messages
  # 
  # @param [Hash] opts the optional parameters
  # @return [Response]
  describe 'get_info test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_release_id
  # Retrieves release id of the KIE container with given id
  # 
  # @param id Container id that release id should be loaded from
  # @param [Hash] opts the optional parameters
  # @return [Response]
  describe 'get_release_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_scanner_info
  # Retrieves scanner information for given container
  # 
  # @param id Container id for scanner to be loaded
  # @param [Hash] opts the optional parameters
  # @return [Response]
  describe 'get_scanner_info test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_server_state
  # Retrieves server state - configuration that the server is currently running with
  # 
  # @param [Hash] opts the optional parameters
  # @return [Response]
  describe 'get_server_state test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for healthcheck
  # Liveness check for KIE Server that validates both kie server and all extensions, optionally produces report
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :report optional report flag to return detailed report of the check, defaults to false
  # @return [Array<KieMessage>]
  describe 'healthcheck test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_containers
  # Retrieves containers deployed to this server, optionally filtered by group, artifact, version or status
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :group_id optional groupId to filter containers by
  # @option opts [String] :artifact_id optional artifactId to filter containers by
  # @option opts [String] :version optional version to filter containers by
  # @option opts [String] :status optional status to filter containers by
  # @return [Response]
  describe 'list_containers test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for readycheck
  # Readiness check for KIE Server that indicates that server is fully booted and ready to accept requests
  # 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'readycheck test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_release_id
  # Updates release id of the KIE container with given id to provided release id
  # 
  # @param id Container id that release id should be upgraded
  # @param body Release Id to be upgraded to as ReleaseId type
  # @param [Hash] opts the optional parameters
  # @return [Response]
  describe 'update_release_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_scanner
  # Updates scanner for given container
  # 
  # @param id Container id for scanner to be updated
  # @param body Scanner information given as KieScannerResource type
  # @param [Hash] opts the optional parameters
  # @return [Response]
  describe 'update_scanner test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
