=begin
#jbpm

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 7.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for JBPMAPIClient::ProcessDefinitionAndInstanceImagesBPMApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ProcessDefinitionAndInstanceImagesBPMApi' do
  before do
    # run before each test
    @instance = JBPMAPIClient::ProcessDefinitionAndInstanceImagesBPMApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProcessDefinitionAndInstanceImagesBPMApi' do
    it 'should create an instance of ProcessDefinitionAndInstanceImagesBPMApi' do
      expect(@instance).to be_instance_of(JBPMAPIClient::ProcessDefinitionAndInstanceImagesBPMApi)
    end
  end

  # unit tests for get_process_image
  # Retrieves process definition image
  # 
  # @param id container id that process definition belongs to
  # @param p_id identifier of the process definition that image should be loaded for
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'get_process_image test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_process_instance_image
  # Retrieves process instance image
  # 
  # @param id container id that process instance belongs to
  # @param p_instance_id identifier of the process instance that image should be loaded for
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'get_process_instance_image test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
