=begin
#jbpm

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 7.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for JBPMAPIClient::TaskEventInstanceList
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TaskEventInstanceList' do
  before do
    # run before each test
    @instance = JBPMAPIClient::TaskEventInstanceList.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TaskEventInstanceList' do
    it 'should create an instance of TaskEventInstanceList' do
      expect(@instance).to be_instance_of(JBPMAPIClient::TaskEventInstanceList)
    end
  end
  describe 'test attribute "task_event_instance"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

